version: "3"
services:
  rundeck:
    image: rundeck/rundeck:4.6.1
    ports:
      - 4440:4440
    environment:
      RUNDECK_GRAILS_URL: http://localhost:4440
    tty: true
    volumes:
      - ./data/rundeck:/home/rundeck/server/data
      - ./configs/rundeck/remco/templates/rundeck-config.properties:/etc/remco/templates/rundeck-config.properties
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4440"]
      interval: 30s
      timeout: 10s
      retries: 5
  rundeck_exporter:
    image: phsmith/rundeck-exporter:latest
    ports:
      - 9620:9620
    environment:
      RUNDECK_EXPORTER_DEBUG: "False"
      RUNDECK_EXPORTER_HOST: 0.0.0.0
      RUNDECK_EXPORTER_PORT: 9620
      RUNDECK_URL: "http://rundeck:4440"
      RUNDECK_TOKEN: "PLACE_RUNDECK_API_TOKEN_HERE"
      RUNDECK_API_VERSION: 40
      RUNDECK_SKIP_SSL: "False"
      RUNDECK_PROJECTS_EXECUTIONS: "True"
      # RUNDECK_PROJECTS_FILTER: "" #space separed
      # RUNDECK_PROJECTS_EXECUTIONS_CACHE: "True"
      # RUNDECK_CACHED_REQUESTS_TTL: 120
      RUNDECK_CPU_STATS: "True"
      RUNDECK_MEMORY_STATS: "True"
    depends_on:
      rundeck:
        condition: service_healthy
    links:
      - rundeck
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    links:
      - rundeck_exporter
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    links:
      - prometheus
